name: clashnode 更新
on:
  schedule:
    # 每天晚上22点执行一次
    - cron:  0 22 * * *

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set git config
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
      - name: Run script
        shell: bash
        run: |
          # 获取当前日期信息
          YEAR=$(date +%Y)
          MONTH=$(date +%m)
          DAY=$(date +%d)
          #DAY=16
          
          # 构造 URL
          URL="https://clashnode.com/wp-content/uploads/${YEAR}/${MONTH}/${YEAR}${MONTH}${DAY}.yaml"
          
          # 下载 YAML 文件
          curl -s $URL > temp.yaml
          
          # 查看第一个句子是否为 port: 7890
          FIRST_LINE=$(head -n 1 temp.yaml)
          if [[ $FIRST_LINE == port:* ]]; then
            # 如果是,将文件内容写入 clash.yaml
            cat temp.yaml > clashnode.yaml
            sed -i '1,/type: select/s/type: select/type: load-balance\
              url: http:\/\/www.gstatic.com\/generate_204\
              interval: 1200/' clashnode.yaml
            sed -i "$(awk '/DIRECT/{print NR}' clashnode.yaml|head -n 1) d" clashnode.yaml
            sed -i "s/节点选择/"$(date +'%Y-%m-%d')"/g" clashnode.yaml
            echo "YAML file downloaded and saved as clashnode.yaml"
          else
            echo "YAML file did not match the condition. Delete temp.yaml and exit."
            rm temp.yaml
            exit
          fi
          # 删除临时文件 temp.yaml
          rm temp.yaml

      - name: Add and commit
        run: |
          git add .
          git commit -m "Add generated files"     

      - name: Push changes
        run: |
          git push origin HEAD:$GITHUB_REF
