name: clashnode 更新
on:
  schedule:
    # 每天东八区10点30执行一次
    - cron:  30 2 * * *
  workflow_dispatch:

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Set git config
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
      - name: Run script
        shell: bash
        run: |
          # 获取当前日期信息
          YEAR=$(date +%Y)
          MONTH=$(date +%m)
          DAY=$(date +%d)
          #DAY=17
          
          # 构造 URL
          URL="https://clashnode.com/wp-content/uploads/${YEAR}/${MONTH}/${YEAR}${MONTH}${DAY}.yaml"
          URLV2ray="https://sub.back2me.cn/sub?target=clash&url=https%3A%2F%2Fclashnode.com%2Fwp-content%2Fuploads%2F${YEAR}%2F${MONTH}%2F${YEAR}${MONTH}${DAY}.txt"
          
          # 下载 YAML 文件
          curl -s $URL > temp.yaml
          if grep -q '????' temp.yaml; then
           curl -s $URLV2ray > temp.yaml
          fi
          
          
          # 查看第一个句子是否为 port: 7890
          FIRST_LINE=$(head -n 1 temp.yaml)
          if [[ $FIRST_LINE == port:* ]]; then
            # 如果是,将文件内容写入 clashnode.yaml
            sed -i '1,/type: select/s/type: select/type: load-balance\
              strategy: round-robin\
              url: http:\/\/www.gstatic.com\/generate_204\
              interval: 600/' temp.yaml
            sed -i "$(awk '/DIRECT/{print NR}' temp.yaml|head -n 1) d" temp.yaml
            sed -i "s/节点选择/"$(date +'%Y-%m-%d')"/g" temp.yaml
            sed -i "s/type: ss,/type: trojan,/g" temp.yaml
            cat temp.yaml | tr '\n' '#' > clashnode.yaml
            sed -i 's/全球直连#    type: select#    proxies:#  - name/全球直连#    type: select#    proxies:#      - DIRECT#  - name/g' clashnode.yaml
            cat clashnode.yaml | tr '#' '\n' > temp.yaml
            cat temp.yaml > clashnode.yaml
            echo "YAML file downloaded and saved as clashnode.yaml"
          else
            echo "YAML file did not match the condition. Delete temp.yaml and exit."
            echo $FIRST_LINE
            rm temp.yaml
            exit
          fi
          # 删除临时文件 temp.yaml
          rm temp.yaml

      - name: Add and commit
        run: |
          git add .
          git commit -m "Add generated files"     

      - name: Push changes
        run: |
          git push origin HEAD:$GITHUB_REF
